/// Handles phone-to-email identity mapping for AQ API calls.
///
/// When the TIDI backend doesn't provide an email for a phone-based user,
/// this service generates a deterministic synthetic email so AQ API calls
/// can proceed without failure.
class UserIdentityService {
  UserIdentityService._();

  static const String _noEmailDomain = 'noemail.alphaquark.in';

  /// Generate a deterministic synthetic email from a phone number.
  ///
  /// The result is stable for a given phone — calling this twice with the
  /// same number always returns the same email.
  static String generateSyntheticEmail(String phone, {String advisor = 'tidi'}) {
    final cleanPhone = phone.replaceAll(RegExp(r'\D'), '');
    return 'phone_91$cleanPhone@$advisor.$_noEmailDomain';
  }

  /// Returns `true` if [email] was generated by [generateSyntheticEmail].
  static bool isSyntheticEmail(String? email) {
    return email != null && email.contains('.$_noEmailDomain');
  }

  /// Extract the phone number from a synthetic email, or `null` if it
  /// isn't a synthetic email.
  static String? extractPhoneFromEmail(String email) {
    final match = RegExp(r'^phone_91(\d+)@').firstMatch(email);
    return match?.group(1);
  }

  /// Return a user-friendly display identifier.
  ///
  /// * If the email is real (not synthetic), returns the email.
  /// * Otherwise falls back to the phone number.
  static String getDisplayId(String? email, String? phone) {
    if (email != null && email.isNotEmpty && !isSyntheticEmail(email)) {
      return email;
    }
    if (phone != null && phone.isNotEmpty) return phone;
    return email ?? 'Unknown';
  }
}
